- name: Add APT key
  apt_key: url=http://docs.mongodb.org/10gen-gpg-key.asc id=7F0CEB10

- name: Add APT repository
  apt_repository: repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' update_cache=yes

- name: Install mongodb-org
  apt: pkg={{item}}
  with_items:
    - python-selinux
    - python-pymongo
    - mongodb-10gen